title = "Hallo"
base_url = "https://www.gallus-domesticus.com"

compile_sass = true
highlight_code = false
build_search_index = false
theme = "hallo"

[extra]
greeting = "Hello!"

iam = "I am"

links = [
    { title = "Blog", url = "https://www.gallus-domesticus.com/blog", iconset = "fas", icon = "blog" },
    { title = "GitHub", url = "https://github.com/hadjilucasL", icon = "github" },
    { title = "Twitter", url = "https://twitter.com/Hadjilucas", icon = "twitter" }
]

[extra.author]
name = "Lucas"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"